language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: E6fF2ULcPPfOi+1uJ8U9KZ+sJp67J1LeKsDedRtRcngKD3jZXeOkEuWx0HFyGHSc6VuA/DSjFj6NcIZaF2gWU+fHRJ2WOhQ5jmFB5Nqyae0kxL3AKQgaJJtyUmXOy1Is5yEjntyHIfF5fqN4RrbA3nNfzc4L68LrZKppfG7WMbzMMrzwUa/gVxToQ5FgM+UqTVtomso9zYopsWJVHBGTpsIsju6+RVwQqr+cVOqE7gcwYMIXt8YmT3CmBVfrTzdQG6y3ySRGnbyc6gNJ9A2qpKmgnQzxWR16jm9Ft79kaaa2PhwjrkFJTr408ps68DoPSO+EiWBlkbvAfRGoFzpLAeXteTYvU0zdBFW48hiPntwYTeCsHq2YdFfDdnkQIT25phOQqSuKkXK0JiB9zQ0ADdp9GKRz6TMYYsQa/Y9Lm7ulTGLQx1rHBnTgyxkwSim5lF1hL5so2f78pWNKowGavvp490WNzZu87QaVAIVmMxmY2KEI0IYN4zW2DT5ebI+K39oUfZGBZDV+Y9X1x79RumOZR6ZaCH/Q7gIdJEhaAIy5+UYqVsiX/qGiDTux1zg+8WN5xUyvzEwUobAiRyqKS6SYmURm7l5iY1AHhbYczpXGij3FrR6NXlT8ljQfFIH1Jdv/Ra59mEkPwQMWklnsOdXqYEOqqgHUHfKsfyN4UaM=
